Rename 'httpms' to 'euterpe' in tools and documentation

diff --git a/tools/install b/tools/install
--- a/tools/install
+++ b/tools/install
@@ -3,27 +3,26 @@ INSTALL_DIR=$(dirname `readlink -f $0`)
 cd "$INSTALL_DIR"
 cd ..
 
-if [ -d /etc/httpms ]; then
-    echo "HTTPMS is already installed. Aborting."
+if [ -d /etc/euterpe ]; then
+    echo "Euterpe is already installed. Aborting."
     exit 0
 fi
 
-for binary in httpms
+for binary in euterpe
 do
     if [ -f "/usr/bin/${binary}" ]; then
-        echo "HTTPMS is already installed. Aborting."
+        echo "Euterpe is already installed. Aborting."
         exit 0
     fi
 done
 
-echo "Installing httpms dir to /etc/..."
-cp -a "$INSTALL_DIR" /etc/httpms || exit 1
+echo "Installing euterpe dir to /etc/..."
+cp -a "$INSTALL_DIR" /etc/euterpe || exit 1
 
 echo "Setting directory permissions..."
-find /etc/httpms -type d -exec chmod 755 "{}" \; || exit 1
+find /etc/euterpe -type d -exec chmod 755 "{}" \; || exit 1
 
 echo "Moving binaries to /usr/bin/..."
-mv /etc/httpms/httpms /usr/bin/httpms || exit 1
+mv /etc/euterpe/euterpe /usr/bin/euterpe || exit 1
 
 echo "Done"
-
